/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAfficheRouteImport } from './routes/_authenticated/affiche'
import { Route as AuthenticatedRegistreRouteImport } from './routes/_authenticated/registre'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites'
import { Route as AuthenticatedStatistiquesRouteImport } from './routes/_authenticated/statistiques'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAfficheRoute = AuthenticatedAfficheRouteImport.update({
  id: '/affiche',
  path: '/affiche',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistreRoute = AuthenticatedRegistreRouteImport.update({
  id: '/registre',
  path: '/registre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatistiquesRoute =
  AuthenticatedStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/affiche': typeof AuthenticatedAfficheRoute
  '/registre': typeof AuthenticatedRegistreRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/affiche': typeof AuthenticatedAfficheRoute
  '/registre': typeof AuthenticatedRegistreRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/affiche': typeof AuthenticatedAfficheRoute
  '/_authenticated/registre': typeof AuthenticatedRegistreRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/_authenticated/statistiques': typeof AuthenticatedStatistiquesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkin'
    | '/reset-password'
    | '/affiche'
    | '/registre'
    | '/sites'
    | '/statistiques'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkin'
    | '/reset-password'
    | '/affiche'
    | '/registre'
    | '/sites'
    | '/statistiques'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkin'
    | '/reset-password'
    | '/_authenticated/affiche'
    | '/_authenticated/registre'
    | '/_authenticated/sites'
    | '/_authenticated/statistiques'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckinRoute: typeof CheckinRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/affiche': {
      id: '/_authenticated/affiche'
      path: '/affiche'
      fullPath: '/affiche'
      preLoaderRoute: typeof AuthenticatedAfficheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registre': {
      id: '/_authenticated/registre'
      path: '/registre'
      fullPath: '/registre'
      preLoaderRoute: typeof AuthenticatedRegistreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistiques': {
      id: '/_authenticated/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AuthenticatedStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAfficheRoute: typeof AuthenticatedAfficheRoute
  AuthenticatedRegistreRoute: typeof AuthenticatedRegistreRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedStatistiquesRoute: typeof AuthenticatedStatistiquesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAfficheRoute: AuthenticatedAfficheRoute,
  AuthenticatedRegistreRoute: AuthenticatedRegistreRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedStatistiquesRoute: AuthenticatedStatistiquesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckinRoute: CheckinRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
