/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AuthenticatedRegistreRouteImport } from './routes/_authenticated/registre'
import { Route as AuthenticatedReglagesRouteImport } from './routes/_authenticated/reglages'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegistreRoute = AuthenticatedRegistreRouteImport.update({
  id: '/registre',
  path: '/registre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReglagesRoute = AuthenticatedReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/registre': typeof AuthenticatedRegistreRoute
  '/reglages': typeof AuthenticatedReglagesRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/registre': typeof AuthenticatedRegistreRoute
  '/reglages': typeof AuthenticatedReglagesRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/_authenticated/registre': typeof AuthenticatedRegistreRoute
  '/_authenticated/reglages': typeof AuthenticatedReglagesRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkin'
    | '/registre'
    | '/reglages'
    | '/api/public/bootstrap-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkin'
    | '/registre'
    | '/reglages'
    | '/api/public/bootstrap-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkin'
    | '/_authenticated/registre'
    | '/_authenticated/reglages'
    | '/api/public/bootstrap-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckinRoute: typeof CheckinRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/registre': {
      id: '/_authenticated/registre'
      path: '/registre'
      fullPath: '/registre'
      preLoaderRoute: typeof AuthenticatedRegistreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reglages': {
      id: '/_authenticated/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof AuthenticatedReglagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRegistreRoute: typeof AuthenticatedRegistreRoute
  AuthenticatedReglagesRoute: typeof AuthenticatedReglagesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRegistreRoute: AuthenticatedRegistreRoute,
  AuthenticatedReglagesRoute: AuthenticatedReglagesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckinRoute: CheckinRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
